continue_train: false
load_checkpoint: null
dataroot: ./datasets/UAV-SC
checkpoints_dir: ./datasets/checkpoints
gpu_ids:
- 0
name: make_run_o
model: pix2pix
isTrain: true
input_nc: 3
output_nc: 3
netG: unet_256
netD: attention_n_layers
n_layers_D: 4
norm: instance
use_SN_D: true
use_SN_G: false
dropout_G: 0.1
dropout_D: 0.1
init_type: normal
init_gain: 0.02
dataset_mode: aligned
direction: AtoB
num_threads: 4
batch_size: 1
num_workers: 4
prefetch_factor: 6
max_dataset_size: 9223372036854775807
no_flip: false
display_winsize: 512
lambda_selected_loss: 20.0
epoch: '200'
load_iter: 0
verbose: true
suffix: ''
train_only_D: false
lambda_laplacian_loss: 0.0
display_id: 0
display_port: 8097
display_ncols: 4
display_server: http://localhost
display_env: main
update_html_freq: 1000
print_freq: 10
type_loss: VGG
relativisticD: false
residual_network: false
use_DEM: false
no_html: true
save_latest_freq: 5000
save_epoch_freq: 10
save_by_iter: false
epoch_count: 250
phase: train
epoch_count_decay: 250
beta1: 0.5
beta2: 0.999
lr: 0.01
gan_mode: hinge
cosine_warmup_T_mult: null
cosine_warmup_eta_min: null
pool_size: 0
lr_policy: cosine
lr_decay_iters: 250
use_gammas: true
attention_layer_depth:
- 32
- 16
use_shadow_attention: true
zero_shadows_in_D: true
aug_crop_size: 256
lrG: 0.0002
lrD: 0.0002
D_steps_per_G: 1
D_warmup_D_steps: 2
D_warmup_epochs: 0
label_smooth_real: 1.0
num_samples: 9223372036854775807
r1_gamma: 0.0
ngf: 64
ndf: 64
D_steps_per_G_current: 2
clearml_project: deshadow
additional_lambda_l1: 2
gen_attn_dec: null
zero_shadows_in_G: false
type_loss_G_colour: VGG
lambda_color_consistency: 1
